### ISSUE TITLE
fix: unable to save payumoney as an active gateway

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give-payumoney#18]
# Bug Report

## User Story
As a user, I want to enable a PayUMoney as payment gateway so that the new user's onboarding with Give can be better UX.

**Note:** This issue was noticed during the DoAction event Ahmedabad 2019.

## Current Behavior
**Check GIF:** ![gif](http://recordit.co/cjpdlf51HE.gif)

## Expected Behavior
I expect to enable PayUMoney payment gateway to start processing donations

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Give and Give - PayUMoney
2. Try activating the PayUMoney gateways as shown in the GIF above.

## Acceptance Criteria
- [x] Reproduce the issue
- [x] PayUMoney gateway should get active irrespective of the dependencies to avoid confusion for first-time users.
- [x] PayUMoney Gateway should enable when USD is set as the base currency and currency switcher is installed.
- [x] Display an error notice when USD is set as a base currency and currency switcher add-on is not installed.
- [x] After fixing the issue test the donations are processed properly or not. If not, then create another issue to solve that.
- [x] Remove unnecessary dependencies which are creating confusion

**Comment by mehul0810** [comment]
@DevinWalker @mikejhale @ravinderk 
After doing research on this issue, I've noticed that we are restricting the payment gateway activation based on the currency selection. So, for example, if USD is the default currency then PayUMoney gateway will not activate at all and will throw an error. 

Here are some of the areas which I think need to be improved:
1. If currency switcher is used and currencies activated are USD (default), INR, JPY. Then, there is no option to activate the PayUMoney payment gateway which is an issue.
2. Adding an admin tooltip and text to better explain what currencies the PayUMoney gateway support as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/1852711/64867986-1938d100-d65c-11e9-8643-e4f9d4a97c53.png)

Let me know your thoughts on whether I should proceed on my findings.

**Comment by mikejhale** [comment]
@mehul0810 I've tested this and the following worked as expected:

- [x] PayUMoney gateway should get active irrespective of the dependencies to avoid confusion for first-time users.
- [x] PayUMoney Gateway should enable when USD is set as the base currency and currency switcher is installed.
- [x] Display an error notice when USD is set as a base currency and currency switcher add-on is not installed.
- [x] Display an error notice when Non-INR (Brazilian Rel) is set as a base currency and currency switcher add-on is not installed.

However I've been unable to create a test Payumoney account. It won't send me the verification code, which I'm thinking may be due to a US number. 

Also I noticed the admin notification is not displayed if Currency Switcher is installed, but it doesn't matter if it is enabled in the `Settings > Currency Switcher > General` settings or if `Indian Rupee (₹)` is enabled as an accepted currency when enabled.
